[package]
name = "tpt-audio-desktop"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[features]
default = []
archon = ["dep:tpt-audio-platform-archon"]

[dependencies]
tpt-audio-core = { path = "../core" }
tpt-audio-gui = { path = "../gui" }
tpt-audio-platform-archon = { path = "../platform-archon", optional = true }
eframe = "0.31"
egui = "0.31"

[target.'cfg(target_os = "windows")'.dependencies]
tpt-audio-platform-windows = { path = "../platform-windows" }

[target.'cfg(target_os = "linux")'.dependencies]
tpt-audio-platform-linux = { path = "../platform-linux" }
